# Setup
title:              Я люблю ИП

# Permalinks
permalink:          pretty

# Sass
sass:
  sass_dir: _sass

# Collections
collections:
  kb:
    output: true
    permalink: /kb/:path/

# Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: "" # empty string for all files
      type: "kb"
    values:
      layout: "post"
      date: "2014-08-01"
